#!/bin/sh
#
# @name DASC Lab 5" Vision Quadrotor SITL
#
# @type Quadrotor
#
# @maintainer Dev
#

. ${R}etc/init.d/rc.mc_defaults

# set MIXER quad_w


echo "************"
echo "SET MIXER TO QUAD RAW"
echo "************"
set MIXER quad_raw
