/*
 * This file was autogenerated by OSQP-Python on October 21, 2022 at 12:11:41.
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "qdldl_interface.h"

// Define data structure
c_int Pdata_i[10] = {
0,
0,
1,
0,
1,
2,
0,
1,
2,
3,
};
c_int Pdata_p[5] = {
0,
1,
3,
6,
10,
};
c_float Pdata_x[10] = {
(c_float)0.18632775557178593573,
(c_float)0.16310043703762008849,
(c_float)0.16351787344762380716,
(c_float)0.18801560136866851680,
(c_float)0.20738454767796993261,
(c_float)0.33209636075693677038,
(c_float)0.13095872534237409934,
(c_float)0.12846980145768741033,
(c_float)0.18093282286191703090,
(c_float)0.10929161570006164228,
};
csc Pdata = {10, 4, 4, Pdata_p, Pdata_i, Pdata_x, -1};
c_int Adata_i[4] = {
0,
1,
2,
3,
};
c_int Adata_p[5] = {
0,
1,
2,
3,
4,
};
c_float Adata_x[4] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000022204,
(c_float)1.00000000000000000000,
};
csc Adata = {4, 4, 4, Adata_p, Adata_i, Adata_x, -1};
c_float qdata[4] = {
(c_float)0.86548400311251072470,
(c_float)0.80993937655462866498,
(c_float)1.00000000000000000000,
(c_float)0.65027997381137192523,
};
c_float ldata[4] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
};
c_float udata[4] = {
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.53568345279424178784,
(c_float)10.00000000000000000000,
};
OSQPData data = {4, 4, &Pdata, &Adata, qdata, ldata, udata};

// Define settings structure
OSQPSettings settings = {(c_float)0.10000000000000000555, (c_float)0.00000100000000000000, 10, 1, 0, (c_float)5.00000000000000000000, 4000, (c_float)0.00100000000000000002, (c_float)0.00100000000000000002, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)1.60000000000000008882, (enum linsys_solver_type) LINSYS_SOLVER, 0, 25, 1, };

// Define scaling structure
c_float Dscaling[4] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)0.94915532008963621191,
(c_float)1.00000000000000000000,
};
c_float Dinvscaling[4] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.05356834527942400115,
(c_float)1.00000000000000000000,
};
c_float Escaling[4] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.05356834527942422319,
(c_float)1.00000000000000000000,
};
c_float Einvscaling[4] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)0.94915532008963598987,
(c_float)1.00000000000000000000,
};
OSQPScaling scaling = {(c_float)0.29918422379257630928, Dscaling, Escaling, (c_float)3.34242222843039193947, Dinvscaling, Einvscaling};

// Define linsys_solver structure
c_int linsys_solver_L_i[10] = {
7,
4,
5,
6,
5,
6,
7,
6,
7,
7,
};
c_int linsys_solver_L_p[9] = {
0,
1,
2,
3,
4,
7,
9,
10,
10,
};
c_float linsys_solver_L_x[10] = {
(c_float)-0.10000000000000000555,
(c_float)-0.10000000000000000555,
(c_float)-0.10000000000000003331,
(c_float)-0.10000000000000000555,
(c_float)0.78698176325950719434,
(c_float)0.48751650983063898881,
(c_float)0.61893265899240201833,
(c_float)0.29688563841677856336,
(c_float)0.22187006561367000890,
(c_float)0.27433689030327057523,
};
csc linsys_solver_L = {10, 8, 8, linsys_solver_L_p, linsys_solver_L_i, linsys_solver_L_x, -1};
c_float linsys_solver_Dinv[8] = {
(c_float)-0.10000000000000000555,
(c_float)-0.10000000000000000555,
(c_float)-0.10000000000000000555,
(c_float)-0.10000000000000000555,
(c_float)3.79479460775228627512,
(c_float)3.71899976028910517201,
(c_float)8.13264311014344798423,
(c_float)6.13911332785330010609,
};
c_int linsys_solver_P[8] = {
4,
5,
6,
7,
1,
2,
3,
0,
};
c_float linsys_solver_bp[8];
c_float linsys_solver_sol[8];
c_float linsys_solver_rho_inv_vec[4] = {
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
c_int linsys_solver_Pdiag_idx[4] = {
0,
2,
5,
9,
};
c_int linsys_solver_KKT_i[18] = {
0,
1,
2,
3,
4,
1,
4,
5,
2,
4,
5,
6,
3,
7,
4,
5,
6,
0,
};
c_int linsys_solver_KKT_p[9] = {
0,
1,
2,
3,
4,
6,
9,
13,
18,
};
c_float linsys_solver_KKT_x[18] = {
(c_float)-10.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)-10.00000000000000000000,
(c_float)0.16351887344762380816,
(c_float)1.00000000000000000000,
(c_float)0.20738454767796993261,
(c_float)0.33209736075693674362,
(c_float)1.00000000000000022204,
(c_float)0.12846980145768741033,
(c_float)0.18093282286191703090,
(c_float)0.10929261570006164328,
(c_float)1.00000000000000000000,
(c_float)0.18632875557178593673,
(c_float)0.16310043703762008849,
(c_float)0.18801560136866851680,
(c_float)0.13095872534237409934,
(c_float)1.00000000000000000000,
};
csc linsys_solver_KKT = {18, 8, 8, linsys_solver_KKT_p, linsys_solver_KKT_i, linsys_solver_KKT_x, -1};
c_int linsys_solver_PtoKKT[10] = {
13,
14,
4,
15,
6,
7,
16,
9,
10,
11,
};
c_int linsys_solver_AtoKKT[4] = {
17,
5,
8,
12,
};
c_int linsys_solver_rhotoKKT[4] = {
0,
1,
2,
3,
};
QDLDL_float linsys_solver_D[8] = {
-10,
-10,
-10,
-10,
0,
0,
0,
0,
};
QDLDL_int linsys_solver_etree[8] = {
7,
4,
5,
6,
5,
6,
7,
-1,
};
QDLDL_int linsys_solver_Lnz[8] = {
1,
1,
1,
1,
3,
2,
1,
0,
};
QDLDL_int   linsys_solver_iwork[24];
QDLDL_bool  linsys_solver_bwork[8];
QDLDL_float linsys_solver_fwork[8];
qdldl_solver linsys_solver = {QDLDL_SOLVER, &solve_linsys_qdldl, &update_linsys_solver_matrices_qdldl, &update_linsys_solver_rho_vec_qdldl, &linsys_solver_L, linsys_solver_Dinv, linsys_solver_P, linsys_solver_bp, linsys_solver_sol, linsys_solver_rho_inv_vec, (c_float)0.00000100000000000000, 4, 4, linsys_solver_Pdiag_idx, 4, &linsys_solver_KKT, linsys_solver_PtoKKT, linsys_solver_AtoKKT, linsys_solver_rhotoKKT, linsys_solver_D, linsys_solver_etree, linsys_solver_Lnz, linsys_solver_iwork, linsys_solver_bwork, linsys_solver_fwork, };

// Define solution
c_float xsolution[4];
c_float ysolution[4];

OSQPSolution solution = {xsolution, ysolution};

// Define info
OSQPInfo info = {0, "Unsolved", OSQP_UNSOLVED, 0.0, 0.0, 0.0};

// Define workspace
c_float work_rho_vec[4] = {
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
};
c_float work_rho_inv_vec[4] = {
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
c_int work_constr_type[4] = {
0,
0,
0,
0,
};
c_float work_x[4];
c_float work_y[4];
c_float work_z[4];
c_float work_xz_tilde[8];
c_float work_x_prev[4];
c_float work_z_prev[4];
c_float work_Ax[4];
c_float work_Px[4];
c_float work_Aty[4];
c_float work_delta_y[4];
c_float work_Atdelta_y[4];
c_float work_delta_x[4];
c_float work_Pdelta_x[4];
c_float work_Adelta_x[4];
c_float work_D_temp[4];
c_float work_D_temp_A[4];
c_float work_E_temp[4];

OSQPWorkspace workspace = {
&data, (LinSysSolver *)&linsys_solver,
work_rho_vec, work_rho_inv_vec,
work_constr_type,
work_x, work_y, work_z, work_xz_tilde,
work_x_prev, work_z_prev,
work_Ax, work_Px, work_Aty,
work_delta_y, work_Atdelta_y,
work_delta_x, work_Pdelta_x, work_Adelta_x,
work_D_temp, work_D_temp_A, work_E_temp,
&settings, &scaling, &solution, &info};

