#include <parameters/param.h>

PARAM_DEFINE_FLOAT(INDI_QUAD_MASS, 1.5f);

PARAM_DEFINE_FLOAT(INDI_THRUST_K, 5.48e-06f);
PARAM_DEFINE_FLOAT(INDI_TORQUE_K, 0.06f);

PARAM_DEFINE_FLOAT(INDI_JXX, 0.03f);
PARAM_DEFINE_FLOAT(INDI_JXY, 0.0f);
PARAM_DEFINE_FLOAT(INDI_JXZ, 0.0f);
PARAM_DEFINE_FLOAT(INDI_JYY, 0.03f);
PARAM_DEFINE_FLOAT(INDI_JYZ, 0.0f);
PARAM_DEFINE_FLOAT(INDI_JZZ, 0.055f);
