#include <parameters/param.h>

PARAM_DEFINE_FLOAT(INDI_QUAD_MASS, 1.0f);

PARAM_DEFINE_FLOAT(INDI_THRUST_K, 0.05f);
PARAM_DEFINE_FLOAT(INDI_TORQUE_K, 1.0f);

PARAM_DEFINE_FLOAT(INDI_JXX, 0.03f);
PARAM_DEFINE_FLOAT(INDI_JXY, 0.0f);
PARAM_DEFINE_FLOAT(INDI_JXZ, 0.0f);
PARAM_DEFINE_FLOAT(INDI_JYY, 0.03f);
PARAM_DEFINE_FLOAT(INDI_JYZ, 0.0f);
PARAM_DEFINE_FLOAT(INDI_JZZ, 0.06f);
